edit workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Titanic Training CI
+name: Titanic CI Pipeline
 
 on:
   push:
@@ -7,44 +7,86 @@ on:
   workflow_dispatch:
 
 jobs:
-
-  train-model:
-
+  train-build-deploy:
     runs-on: ubuntu-latest
 
-    steps:
+    permissions:
+      contents: write
 
+    steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Setup Miniconda
-        uses: conda-incubator/setup-miniconda@v3
+      - name: Setup Python
+        uses: actions/setup-python@v5
         with:
-          auto-update-conda: true
-          python-version: 3.12
+          python-version: "3.12"
 
-      - name: Install MLflow
-        shell: bash -l {0}
+      - name: Install Dependencies
         run: |
-          pip install mlflow==2.19.0
+          python -m pip install --upgrade pip
+          pip install -r MLProject/requirements.txt
+
+      - name: Check Environment
+        run: |
+          python --version
+          pip list
 
       - name: Run MLflow Project
-        shell: bash -l {0}
+        env:
+          MLFLOW_TRACKING_URI: https://dagshub.com/firlanpamungkas/titanic-mlflow.mlflow
+          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
+          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
         run: |
           cd MLProject
-          mlflow run .
+          mlflow run . --env-manager local
 
-      - name: Upload Artifact
+      - name: Read Run ID
+        run: |
+          if [ ! -f MLProject/run_id.txt ]; then
+            echo "run_id.txt not found!"
+            exit 1
+          fi
+
+          RUN_ID=$(cat MLProject/run_id.txt)
+          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
+          echo "Run ID: $RUN_ID"
+
+      - name: Download Artifact
+        env:
+          MLFLOW_TRACKING_URI: https://dagshub.com/firlanpamungkas/titanic-mlflow.mlflow
+          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
+          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
+        run: |
+          mlflow artifacts download \
+            --run-id "$RUN_ID" \
+            -d downloaded_artifacts
+
+      - name: Inspect Artifact Structure
+        run: |
+          echo "=== Artifact Structure ==="
+          ls -R downloaded_artifacts
+
+      - name: Upload Artifact to GitHub
         uses: actions/upload-artifact@v4
         with:
-          name: trained-model
-          path: MLProject/mlruns
+          name: titanic-model
+          path: downloaded_artifacts
+
+      - name: Locate MLflow Model
+        run: |
+          MODEL_PATH=$(find downloaded_artifacts -name MLmodel | head -n 1 | xargs dirname)
+
+          echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
+
+          echo "Detected Model Path:"
+          echo "$MODEL_PATH"
 
       - name: Build Docker Image
         run: |
           mlflow models build-docker \
-          -m MLProject/saved_model \
-          -n titanic-model
+            -m "$MODEL_PATH" \
+            -n titanic-model
 
       - name: Login DockerHub
         uses: docker/login-action@v3
@@ -54,10 +96,14 @@ jobs:
 
       - name: Tag Docker Image
         run: |
-          docker tag titanic-model \
-          firlan/titanic-model:latest
+          docker tag titanic-model firlan/titanic-model:latest
 
       - name: Push Docker Image
         run: |
-          docker push \
-          firlan/titanic-model:latest
+          docker push firlan/titanic-model:latest
+
+      - name: Workflow Completed
+        run: |
+          echo "Training completed"
+          echo "Artifact uploaded"
+          echo "Docker image pushed"
